import DynamicBackground from "@/components/background/DynamicBackground";
import Header from "@/components/header/Header";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${playfairDisplay.variable} font-sans antialiased`}
      >
        <DynamicBackground>
          <Header />
          <main className="flex-1">{children}</main>
        </DynamicBackground>
        <Toaster />
      </body>
    </html>
  );
}
